config/routes.rb
Rails.application.routes.draw do
  resources :goals
  resources :notes
  root 'daily_notes#index', as: 'notes_index'

  resources :teammembers do
    member do
      post 'toggle_ooo'
    end
  end
  resources :teams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/teammember.rb
class Teammember < ApplicationRecord
  belongs_to :team
  has_many :notes
  
  def ooo
    return state == "Out of Office"
  end
  
  def homeoffice
    return state == "In Home Office"
  end
  
  def state_without_whitespace_lowercase
    return state.downcase.gsub(/\s+/, "")
  end
end

app/controllers/teammembers_controller.rb
class TeammembersController < ApplicationController
  before_action :set_teammember, :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teammembers
  # GET /teammembers.json
  def index
    @teammembers = Teammember.all.order(:name)
  end

  # GET /teammembers/1
  # GET /teammembers/1.json
  def show
  end

  # GET /teammembers/new
  def new
    @teammember = Teammember.new
    @teammember.team_id = params[:team_id]
  end

  # GET /teammembers/1/edit
  def edit
  end

  # POST /teammembers
  # POST /teammembers.json
  def create
    @teammember = Teammember.new(teammember_params)

    respond_to do |format|
      if @teammember.save
        format.html { redirect_to @teammember, notice: 'Teammember was successfully created.' }
        format.json { render :show, status: :created, location: @teammember }
      else
        format.html { render :new }
        format.json { render json: @teammember.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teammembers/1
  # PATCH/PUT /teammembers/1.json
  def update
    respond_to do |format|
      if @teammember.update(teammember_params)
        # format.js
        format.html { redirect_to @teammember, notice: 'Teammember was successfully updated.' }
        format.json { render :show, status: :ok, location: @teammember }
      else
        format.html { render :edit }
        format.json { render json: @teammember.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teammembers/1
  # DELETE /teammembers/1.json
  def destroy
    @teammember.destroy
    respond_to do |format|
      format.html { redirect_to teammembers_url, notice: 'Teammember was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_ooo
    @teammember = Teammember.find(params[:id])
    if @teammember.state == "In the Office"
      @teammember.state = "Out of Office"
    elsif @teammember.state == "Out of Office"
       @teammember.state = "In Home Office"
    else
       @teammember.state = "In the Office"
    end
    @teammember.save
    @team = Team.find(1)
    redirect_to notes_index_url

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teammember
      @teammember = Teammember.find(params[:id])
    end

    def set_team
      @team = Team.find(1)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teammember_params
      params.require(:teammember).permit(:name, :team_id, :state)
    end
end

app/helpers/teammembers_helper.rb
module TeammembersHelper
end

app/views/teammembers/_form.html.erb
<%= form_for(teammember, remote: true) do |f| %>
  <% if teammember.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teammember.errors.count, "error") %> prohibited this teammember from being saved:</h2>

      <ul>
      <% teammember.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team %>
    <%= f.text_field :team_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :ooo %>
    <%= f.check_box :ooo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teammembers/_teammember.html.erb
<%= link_to teammember.name, { controller: "teammembers", action: "toggle_ooo", id: teammember }, method: :post, class: 'is_'+teammember.state_without_whitespace_lowercase %>
  <br>

app/views/teammembers/edit.html.erb
<h1>Editing Teammember</h1>

<%= render 'form', teammember: @teammember %>

<%= link_to 'Show', @teammember %> |
<%= link_to 'Back', teammembers_path %>

app/views/teammembers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teammembers (<%= @teammembers.count %>)</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teammembers.each do |teammember| %>
      <tr>
        <td><%= teammember.name %></td>
        <td><%= link_to 'Show', teammember %></td>
        <td><%= link_to 'Edit', edit_teammember_path(teammember) %></td>
        <td><%= link_to 'Destroy', teammember, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teammember', new_teammember_path %>

app/views/teammembers/new.html.erb
<h1>New Teammember</h1>

<%= render 'form', teammember: @teammember %>

<%= link_to 'Back', teammembers_path %>

app/views/teammembers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @teammember.team_id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @teammember.name %>
</p>
<p>
  <strong>OOO:</strong>
  <%= @teammember.ooo %>
</p>

<%= link_to 'Edit', edit_teammember_path(@teammember) %> |
<%= link_to 'Back', teammembers_path %>