config/routes.rb
Rails.application.routes.draw do
  resources :goals
  resources :notes
  root 'daily_notes#index', as: 'notes_index'

  resources :teammembers do
    member do
      post 'toggle_ooo'
    end
  end
  resources :teams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/goal.rb
class Goal < ApplicationRecord
  has_many :notes

  def changed_today?
    year_month_day = '%Y-%m-%d'
    updated_at.strftime(year_month_day) == Date.today.strftime(year_month_day)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to :notes_index, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to :notes_index, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:summary, :link, :due_date, :eta, :hashtag, :priority, :info)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for(goal) do |f| %>
  <% if goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :priority %>
    #<%= f.number_field :priority %>
  </div>

  <div class="field">
    <%= f.label :summary %>
    <%= f.text_field :summary %>
  </div>

  <div class="field">
    <%= f.label :info %>
    <%= f.text_field :info %>
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>

  <div class="field">
    <%= f.label :due_date %>
    <%= f.text_field :due_date %>
  </div>

  <div class="field">
    <%= f.label :eta %>
    <%= f.text_field :eta %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goals/_goal.erb
<% if goal.changed_today? %>
	<li class="updated">
<% else %>
	<li>	
<% end %>
<% if goal.link.blank? %>
<%= goal.summary %><%= '('+goal.info+')' unless goal.info.blank? %>
<% else %>
<%= link_to goal.summary, goal.link %> <%= '('+goal.info+')' unless goal.info.blank? %>
<% end %>

<% if not goal.eta.empty? %>
(ETA: <%= goal.eta%>)
<% end %>

<% if not goal.due_date.empty? %>
(Due: <%= goal.due_date%>)
<% end %>

<span id="goal_buttons"><%= link_to 'Edit', edit_goal_path(goal)%> <%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></span>
</li>
<ul>
<%= render goal.notes %>
</ul>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Goals</h1>

<table>
  <thead>
    <tr>
      <th>Summary</th>
      <th>Link</th>
      <th>Due date</th>
      <th>Eta</th>
	  <th>Prio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.summary %></td>
        <td><%= goal.link %></td>
        <td><%= goal.due_date %></td>
        <td><%= goal.eta %></td>
		 <td><%= goal.priority %></td>
        <td><%= link_to 'Show', goal %></td>
        <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
        <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal', new_goal_path %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Summary:</strong>
  <%= @goal.summary %>
</p>

<p>
  <strong>Link:</strong>
  <%= @goal.link %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @goal.due_date %>
</p>

<p>
  <strong>Eta:</strong>
  <%= @goal.eta %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>